# Generated by Django 2.2.2 on 2020-02-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_auto_20200201_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cpsize',
            field=models.CharField(default=None, max_length=5),
        ),
    ]
