# Generated by Django 2.2.4 on 2020-03-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_city',
            field=models.ForeignKey(default=None, on_delete='CASCADE', to='MyApp.City'),
        ),
    ]
