# Generated by Django 2.2.4 on 2020-03-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_state',
            field=models.ForeignKey(default=None, on_delete='CASCADE', to='MyApp.State'),
        ),
    ]
