# Generated by Django 2.2.4 on 2020-03-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_address_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_state',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
