# Generated by Django 2.2.4 on 2020-03-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0011_auto_20200327_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_address',
            field=models.CharField(default=None, max_length=2000),
        ),
    ]
