# Generated by Django 2.2.4 on 2020-03-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0013_auto_20200327_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelorder',
            name='order_city',
            field=models.CharField(default=None, max_length=2000),
        ),
        migrations.AddField(
            model_name='cancelorder',
            name='order_pin',
            field=models.CharField(default=None, max_length=2000),
        ),
        migrations.AddField(
            model_name='cancelorder',
            name='order_state',
            field=models.CharField(default=None, max_length=2000),
        ),
        migrations.AddField(
            model_name='cancelorder',
            name='status',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='previousorder',
            name='order_city',
            field=models.CharField(default=None, max_length=2000),
        ),
        migrations.AddField(
            model_name='previousorder',
            name='order_pin',
            field=models.CharField(default=None, max_length=2000),
        ),
        migrations.AddField(
            model_name='previousorder',
            name='order_state',
            field=models.CharField(default=None, max_length=2000),
        ),
        migrations.AddField(
            model_name='previousorder',
            name='status',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='cancelorder',
            name='order_address',
            field=models.CharField(default=None, max_length=2000),
        ),
        migrations.AlterField(
            model_name='previousorder',
            name='order_address',
            field=models.CharField(default=None, max_length=2000),
        ),
    ]
